{
  "openapi": "3.0.0",
  "info": {
    "title": "API",
    "description": "API2",
    "termsOfService": "http://localhost:3000/termos",
    "contact": {
      "email": "marciohenr__@hotmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:6001",
      "description": "Servidor de Desenvolvimento"
    }
  ],
  "paths": {
    "/ponto": {
      "post": {
        "summary": "Cadastrar Ponto",
        "description": "Realiza o cadastro de um ponto por nome, posição x e posição y",
        "tags": ["Ponto"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Ponto"
              },
              "examples": {
                "ponto exemplo 01": {
                  "value": {
                    "nome": "Ponto 01",
                    "xPos": "1.3816",
                    "yPos": "4.4479"
                  }
                },
                "ponto exemplo 02": {
                  "value": {
                    "nome": "Ponto 02",
                    "xPos": "1.38516",
                    "yPos": "4.479"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Ponto"
                }
              }
            }
          },
          "400": {
            "description": "Ponto já cadastrado"
          }
        }
      },
      "get": {
        "summary": "Exibe todos pontos e parametros",
        "description": "Busca e exibe todos pontos e seus parametros",
        "tags": ["Ponto"],
        "responses": {
          "200": {
            "description": "Sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Ponto"
                }
              }
            }
          },
          "400": {
            "description": "Ocorreu um erro"
          }
        }
      }
    },
    "/ponto/pesquisar": {
      "get": {
        "summary": "Pesquisar um ponto",
        "description": "Realiza consulta de um ou mais pontos",
        "tags": ["Ponto"],
        "parameters": [
            {
                "name": "nome",
                "in": "query",
                "description": "Nome do ponto",
                "required": true
            }
        ],
        "responses": {
          "200": {
            "description": "Sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Ponto"
                }
              }
            }
          },
          "400": {
            "description": "Informe um termo para pesquisar"
          }
        }
      }
    },    
    "/parametro": {
      "post": {
        "summary": "Cadastrar Parametro",
        "description": "Realiza o cadastro de um ponto por nome, valor, data_coleta e pontosId",
        "tags": ["Parametro"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Parametro"
              },
              "examples": {
                "DBO": {
                  "value": {
                    "nome": "DBO",
                    "valor": 5.1,
                    "data_coleta": "2022-07-15T00:12:48.370Z",
                    "pontosId": ""
                  }
                },
                "Alumínio dissolvido": {
                  "value": {
                    "nome": "Alumínio dissolvido",
                    "valor": 0.1,
                    "data_coleta": "2022-07-15T00:12:48.370Z",
                    "pontosId": ""
                  }
                },
                "Cobre dissolvido": {
                  "value": {
                    "nome": "CCobre dissolvido",
                    "valor": 0.009,
                    "data_coleta": "2022-07-15T00:12:48.370Z",
                    "pontosId": ""
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Parametro"
                }
              }
            }
          },
          "400": {
            "description": "Verifique o campo valor"
          }
        }
      },
      "get": {
        "summary": "Lista todos parametros cadastrados",
        "description": "Busca e exibe todos parametros e seus pontos associados",
        "tags": ["Parametro"],
        "responses": {
          "200": {
            "description": "Sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Parametro"
                }
              }
            }
          },
          "400": {
            "description": "Ocorreu um erro"
          }
        }
      }
    },
    "/parametro/pesquisar": {
        "get": {
          "summary": "Pesquisar um parametro",
          "description": "Busca e exibe um parametro por query string",
          "tags": ["Parametro"],
          "parameters": [
              {
                  "name": "nome",
                  "in": "query",
                  "description": "Nome do parametro",
                  "required": true
              }
          ],
          "responses": {
            "200": {
              "description": "Sucesso",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "$ref": "#/components/schemas/Parametro"
                  }
                }
              }
            },
            "400": {
              "description": "Informe um termo para pesquisar"
            }
          }
        }
    },
    "/parametro/violacoes": {
        "get": {
          "summary": "Exibe todos parametros violados",
          "description": "Busca e exibe todos parametros cadastrados como violados",
          "tags": ["Parametro"],        
          "responses": {
            "200": {
              "description": "Sucesso",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "$ref": "#/components/schemas/Parametro"
                  }
                }
              }
            },
            "400": {
              "description": "Ocorreu um erro"
            }
          }
        }
    },
    "/parametro/referencia": {
        "get": {
          "summary": "Inicializa tabela de parametros de referencia",
          "description": "Faz a inserção na base de dados de todos parametros de referência",
          "tags": ["Parametro"],        
          "responses": {
            "200": {
              "description": "Sucesso"              
            },
            "400": {
              "description": "Tabela já inicializada"
            }
          }
        }
    }
  },
  "components": {
    "schemas": {
      "Ponto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "nome": {
            "type": "string"
          },
          "xPos": {
            "type": "string"
          },
          "yPos": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "Parametros": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "format": "uuid"
              },
              "nome": {
                "type": "string"
              },
              "valor": {
                "type": "number",
                "format": "float"
              },
              "data_coleta": {
                "type": "string",
                "format": "date-time"
              },
              "isViolated": {
                "type": "boolean",
                "default": false
              },
              "pontosId": {
                "type": "string",
                "format": "date-time"
              },
              "createdAt": {
                "type": "string",
                "format": "date-time"
              }
            }
          }
        }
      },
      "Parametro": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "nome": {
            "type": "string"
          },
          "valor": {
            "type": "number",
            "format": "float"
          },
          "data_coleta": {
            "type": "string",
            "format": "date-time"
          },
          "isViolated": {
            "type": "boolean",
            "default": false
          },
          "pontosId": {
            "type": "string",
            "format": "uuid"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "ParametroReferencia": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "parametro": {
            "type": "string"
          },
          "valor": {
            "type": "number",
            "format": "float"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      }
    }
  }
}
